### ISSUE TITLE
Add a Lightbox Pop-Up Modal

### ISSUE THREAD

**Issue by Qoyyuum** [Qoyyuum/tablegenerator#9]
When the code is generated, it should be able to pop-up into a lightbox like modal instead of generating a new tab page for the source code to appear. 

Optionally, add the ability to click to copy to clipboard.

**Comment by NitinNair89** [comment]
Hi,
I would like to attempt and work on this.

**Comment by Qoyyuum** [comment]
> Hi,
> I would like to attempt and work on this.

Go ahead.

**Comment by NitinNair89** [comment]
Thanks, please assign this issue to me. :)

**Comment by NitinNair89** [comment]
Hi @Qoyyuum 
Please review my PR and let me know your suggestions.
